/* xerrno_strerror.c - error value message implementations */

#include <libf/config.h>
#include <libf/sl/xstdint.h>
#include <libf/sl/xerrno.h>


/* @func: strerror - get error message string
* @param1: int32  # errno value
* @return: char * # error message string
*/
char *XSYMBOL(strerror)(int32 n) {
	/* implicit static variable */
	static const char *strerr[XEMAX] = {
	[XEUNDEF] = XEUNDEF_STR,
	[XE2BIG] = XE2BIG_STR,
	[XEACCES] = XEACCES_STR,
	[XEADDRINUSE] = XEADDRINUSE_STR,
	[XEADDRNOTAVAIL] = XEADDRNOTAVAIL_STR,
	[XEAFNOSUPPORT] = XEAFNOSUPPORT_STR,
	[XEAGAIN] = XEAGAIN_STR,
	[XEALREADY] = XEALREADY_STR,
	[XEBADF] = XEBADF_STR,
	[XEBADMSG] = XEBADMSG_STR,
	[XEBUSY] = XEBUSY_STR,
	[XECANCELED] = XECANCELED_STR,
	[XECHILD] = XECHILD_STR,
	[XECONNABORTED] = XECONNABORTED_STR,
	[XECONNREFUSED] = XECONNREFUSED_STR,
	[XECONNRESET] = XECONNRESET_STR,
	[XEDEADLK] = XEDEADLK_STR,
	[XEDESTADDRREQ] = XEDESTADDRREQ_STR,
	[XEDOM] = XEDOM_STR,
	[XEDQUOT] = XEDQUOT_STR,
	[XEEXIST] = XEEXIST_STR,
	[XEFAULT] = XEFAULT_STR,
	[XEFBIG] = XEFBIG_STR,
	[XEHOSTUNREACH] = XEHOSTUNREACH_STR,
	[XEIDRM] = XEIDRM_STR,
	[XEILSEQ] = XEILSEQ_STR,
	[XEINPROGRESS] = XEINPROGRESS_STR,
	[XEINTR] = XEINTR_STR,
	[XEINVAL] = XEINVAL_STR,
	[XEIO] = XEIO_STR,
	[XEISCONN] = XEISCONN_STR,
	[XEISDIR] = XEISDIR_STR,
	[XELOOP] = XELOOP_STR,
	[XEMFILE] = XEMFILE_STR,
	[XEMLINK] = XEMLINK_STR,
	[XEMSGSIZE] = XEMSGSIZE_STR,
	[XEMULTIHOP] = XEMULTIHOP_STR,
	[XENAMETOOLONG] = XENAMETOOLONG_STR,
	[XENETDOWN] = XENETDOWN_STR,
	[XENETRESET] = XENETRESET_STR,
	[XENETUNREACH] = XENETUNREACH_STR,
	[XENFILE] = XENFILE_STR,
	[XENOBUFS] = XENOBUFS_STR,
	[XENODATA] = XENODATA_STR,
	[XENODEV] = XENODEV_STR,
	[XENOENT] = XENOENT_STR,
	[XENOEXEC] = XENOEXEC_STR,
	[XENOLCK] = XENOLCK_STR,
	[XENOLINK] = XENOLINK_STR,
	[XENOMEM] = XENOMEM_STR,
	[XENOMSG] = XENOMSG_STR,
	[XENOPROTOOPT] = XENOPROTOOPT_STR,
	[XENOSPC] = XENOSPC_STR,
	[XENOSR] = XENOSR_STR,
	[XENOSTR] = XENOSTR_STR,
	[XENOSYS] = XENOSYS_STR,
	[XENOTCONN] = XENOTCONN_STR,
	[XENOTDIR] = XENOTDIR_STR,
	[XENOTEMPTY] = XENOTEMPTY_STR,
	[XENOTRECOVERABLE] = XENOTRECOVERABLE_STR,
	[XENOTSOCK] = XENOTSOCK_STR,
	[XENOTSUP] = XENOTSUP_STR,
	[XENOTTY] = XENOTTY_STR,
	[XENXIO] = XENXIO_STR,
	[XEOPNOTSUPP] = XEOPNOTSUPP_STR,
	[XEOVERFLOW] = XEOVERFLOW_STR,
	[XEOWNERDEAD] = XEOWNERDEAD_STR,
	[XEPERM] = XEPERM_STR,
	[XEPIPE] = XEPIPE_STR,
	[XEPROTO] = XEPROTO_STR,
	[XEPROTONOSUPPORT] = XEPROTONOSUPPORT_STR,
	[XEPROTOTYPE] = XEPROTOTYPE_STR,
	[XERANGE] = XERANGE_STR,
	[XEROFS] = XEROFS_STR,
	[XESPIPE] = XESPIPE_STR,
	[XESRCH] = XESRCH_STR,
	[XESTALE] = XESTALE_STR,
	[XETIME] = XETIME_STR,
	[XETIMEDOUT] = XETIMEDOUT_STR,
	[XETXTBSY] = XETXTBSY_STR,
	[XEWOULDBLOCK] = XEWOULDBLOCK_STR,
	[XEXDEV] = XEXDEV_STR,
	};

	n = (n < 0) ? -n : n;
	if (n >= XEMAX)
		return XEMAX_STR;

	return (char *)strerr[n];
} /* end */
